name: 贴吧自动签到

on:
  schedule:
    - cron: "13 1 * * *"  # 北京时间 09:13
  workflow_dispatch:

jobs:
  sign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install requests

      - name: Run sign
        env:
          TIEBA_COOKIE: ${{ secrets.TIEBA_COOKIE }}
        run: python main.py
